Task3
EiadAhmed/bld-task-udemy pull request #3
Opened 2022-08-18 01:35 UTC by EiadAhmed

2022-08-22 09:21 UTC, amrbahaa1 requested changes
Please add folder structure for scripts and styles

2022-08-29 22:03 UTC, EiadAhmed commented
updated

2022-09-05 06:13 UTC, amrbahaa1 reviewed
Good job but try to always use a good naming convention

2022-09-05 06:13 UTC, amrbahaa1 commented on scripts/home.js
> +let a = location.href;
Variable names are not good. Please have a good naming variable.

2022-09-09 18:54 UTC, merged